### ISSUE TITLE
打分OD回合异常

### ISSUE THREAD

**Issue by 332879969** [S1gn/hbr-auto#1]
轴：[[1, 1, 4, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
    [[1, 1, 0, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
    [[1, 1, 0, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
    [[1, 1, 0, 0], [2, 3, 0, 0], [3, 4, 0, 0]],
    [[1, 1, 4, 0], [2, 2, 1, 1], [3, 3, 2, 0]],
    [[1, 4, 1, 0], [2, 2, 2, 0], [3, 3, 0, 0],['O']],
    [[1, 1, 1, 0], [2, 2, 1, 4], [3, 4, 1, 0]],
    [[1, 3, 0, 0], [2, 3, 0, 0], [3, 4, 0, 0]],
    [[1, 1, 0, 0], [2, 2, 3, 0], [3, 4, 0, 0]],
    [[1, 1, 2, 0], [2, 2, 3, 0], [3, 3, 0, 0]],
    [[1, 1, 0, 0], [2, 2, 3, 0], [3, 3, 0, 0]],
    [[1, 1, 2, 0], [2, 2, 3, 0], [3, 4, 1, 1]],
    [[1, 2, 0, 0], [2, 3, 2, 0], [3, 4, 1, 4]],
    [[1, 4, 3, 0], [2, 3, 0, 0], [3, 3, 0, 0]],
    [[1, 4, 2, 0], [2, 2, 2, 0], [3, 3, 3, 0],['O']],
    [[1, 1, 1, 0], [2, 2, 2, 0], [3, 3, 1, 4]],
    [[1, 4, 1, 0], [2, 4, 1, 0], [3, 4, 1, 1
![2024-10-02_141302](https://github.com/user-attachments/assets/0b4d4738-fc9b-4934-a0a5-77f75ed7db76)
]]
![2024-10-02_141900](https://github.com/user-attachments/assets/2fc77c56-e110-4e13-96d2-8b4647998149)

第六回合开od后行动偏离轴，重复了上回合的操作

**Comment by S1gn** [comment]
请pull一下最新的代码，或者看我b站[最新动态](https://www.bilibili.com/opus/981103412439416841)怎么修改，懒人包没有及时更新

**Comment by 332879969** [comment]
好吧，我还以为懒人包已经是最新的了
